//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_test.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Base_Price { get; set; }
        public bool Discount_Indicator { get; set; }
    }
}
